#!/bin/sh -x

# Run tests against gpsfake inside Docker
#
# The following environment variables should be set
#
# RELEASE	# gpsd release, e.g. '3.16'
#
# Markus Juenemann, 20-Feb-2016


RELEASE=${RELEASE:-3.16}

cd /home/developer/src
rm .coverage

chmod 777 /dev/pts

PATH=/opt/gpsd/$RELEASE/bin:/opt/gpsd/$RELEASE/sbin:$PATH \
  PYTHONPATH=/opt/gpsd/$RELEASE/gps \
  GPSD_HOME=/opt/gpsd/$RELEASE/bin \
  python2.7 /opt/gpsd/3.16/bin/gpsfake -c 0.1 -n tests/short.nmea &

sleep 5

chmod -v 666 /dev/pts/*

CPATH=/opt/gpsd/$RELEASE/include TOX_TESTENV_PASSENV=CPATH make tox
