#!/bin/sh -x

# Run tests against gpsfake inside Docker
#
# The following environment variables should be set
#
# BRANCH	# python-gpsdshm branch, e.g. 'master', 'develop'
# RELEASE	# gpsd release, e.g. '3.16'
#
# Markus Juenemann, 20-Feb-2016


BRANCH=${BRANCH:-develop}
RELEASE=${RELEASE:-3.16}


cd /home/developer/python-gpsdshm

git fetch -t

git checkout $BRANCH

git pull origin $BRANCH

PATH=/opt/gpsd/$RELEASE/bin:/opt/gpsd/$RELEASE/sbin:$PATH \
  PYTHONPATH=/opt/gpsd/$RELEASE/gps \
  python2.7 /opt/gpsd/$RELEASE/bin/gpsfake -c 0.1 -n tests/short.nmea &


CPATH=/opt/gpsd/$RELEASE/include TOX_TESTENV_PASSENV=CPATH make tox

pkill -f gps
